version: "3.7"
services:
  backend:
    depends_on:
      - db
    build: ./src/backend
    ports:
      - 420:420
    volumes:
      - ./src/backend:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always

  db:
    container_name: pong_db
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSGRES_PORT=5432
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PG_DATA=/var/lib/postgresql/data
    expose:
      - "5432"
    restart: unless-stopped





  pgadmin:
    depends_on:
      - db
    container_name: pg_admin_container
    image: dpage/pgadmin4:4.24
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
       - pgadmin:/var/lib/pgadmin
       - ./servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:postgres:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"

volumes:
  pg_data:
  pgadmin:

