version: "3.0"
services:
# Backend service
  backend:
    container_name: backend
    build: ./src/backend
    ports:
      - 420:420
    volumes:
      - ./src/backend:/app

# postgres service
  postgres:
    container_name: postgres
    build: "./src/postgres"
    volumes:
      - ./src/postgres/volume_claims/:/var/lib/postgresql/data/

# pg-admin
  pgadmin:
    container_name: pgadmin4
    depends_on:
      - postgres
    build: ./src/pgadmin
    ports:
      - 5050:80
    links:
      - postgres:pgsql-server

# not sure what this does / if we need it?
volumes:
  postgres-data:
