# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  #
#                                                                              #
#               __    __   ______    ______   ________  _______                #
#              /  \  /  | /      \  /      \ /        |/       \               #
#              $$  \ $$ |/$$$$$$  |/$$$$$$  |$$$$$$$$/ $$$$$$$  |              #
#              $$$  \$$ |$$ |  $$/ $$ |  $$ |   $$ |   $$ |__$$ |              #
#              $$$$  $$ |$$ |      $$ |  $$ |   $$ |   $$    $$<               #
#              $$ $$ $$ |$$ |   __ $$ |  $$ |   $$ |   $$$$$$$  |              #
#              $$ |$$$$ |$$ \__/  |$$ \__$$ |   $$ |   $$ |__$$ |              #
#              $$ | $$$ |$$    $$/ $$    $$/    $$ |   $$    $$/               #
#              $$/   $$/  $$$$$$/   $$$$$$/     $$/    $$$$$$$/                #
#                                                                              #
#                                                                              #
#                           New Coders on the Block                            #
#    ——————————————————————————————————————————————————————————————————————    #
#                 Mpeerdem   |   https://github.com/Maqrkk                     #
#                 Rpet       |   https://github.com/rpet91                     #
#                 Mraasvel   |   https://github.com/mraasvel                   #
#                 Ikole      |   https://github.com/K1ngmar                    #
#                 Nvan-aac   |   https://github.com/vanaacken                  #
#                                                                              #
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  #

version: "3.0"
services:
# Frontend Service
  frontend:
    container_name: frontend
    build: ./src/frontend
    depends_on:
      - backend
    volumes:
      - ./src/frontend/app:/app
    ports:
      - 8080:8080
    restart: on-failure
# Backend Service
  backend:
    container_name: backend
    build: ./src/backend
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/backend/app:/app
    env_file:
      - ./src/backend/.env
    ports:
      - 3000:3000
    restart: on-failure
# PostgreSQL Service
  postgres:
    container_name: postgres
    build: ./src/postgres
    env_file:
      - "./src/postgres/postgres.env"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
# PgAdmin (v4) Service
  pgadmin:
    container_name: pgadmin
    build: ./src/pgadmin
    depends_on:
      - postgres
    env_file:
      - "./src/pgadmin/config/pgadmin.env"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 5050:80

volumes:
  pgdata:
  pgadmin_data:
