name: Linter Frontend

on:
# Replace pull_request with pull_request_target if you
# plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-frontend:
    name: Linter Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install CI dependencies
        run: cd ./src/frontend/app && npm ci
      - name: lint
        run: cd ./src/frontend/app && npm run lint:ci
